version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672" 

  app:
    build: .
    container_name: nestjs_blog_app
    ports:
      - "7777:7012"
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo-data:
