name: Blog Service

on:
  push:
    branches:
      - blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Commands to deploy the application on the server
            cd projects/blog-microservice/backend/blog
            git stash
            git pull origin blog --no-ff
            npm run migration
            pm2 stop blog_blog_7012
            pm2 delete blog_blog_7012
            pm2 start "npm run prod" --name blog_blog_7012