name: Blog frontend

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Commands to deploy the application on the server
            cd /projects/blog-microservice/frontend
            git stash
            git pull origin frontend --no-ff
            pm2 stop blog_frontend_7000
            pm2 delete blog_frontend_7000
            pm2 start "serve -s build -l 7000" --name blog_frontend_7000