name: Like Service

on:
  push:
    branches:
      - like

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Commands to deploy the application on the server
            cd projects/blog-microservice/backend/like
            git stash
            git pull origin like --no-ff
            yarn
            yarn build
            pm2 stop blog_like_7014
            pm2 delete blog_like_7014
            pm2 start "npm run prod" --name blog_like_7014